[package]
name = "aoc-2018-rust"
version = "0.1.0"
authors = ["Eshan Singh <eshansingh@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
thiserror = "1.0"
itertools = "0.9"
cached = "0.18"
binary-heap-plus = "0.3"
regex = "1.3"
clap = "2"
z3 = "0.6"
